### ISSUE TITLE
Expand fastcat to be able to use healpix window functions

### ISSUE THREAD

**Issue by slosar** [DarkEnergyScienceCollaboration/2pt_validation#1]
... and then use Humna's output to have a more realistic WF with real instrument inprint.

**Comment by drphilmarshall** [comment]
Nice! @humnaawan and I were just talking about this last week. I think she's up for helping out!

**Comment by slosar** [comment]
I've copied files provided by Humna to

/project/projectdirs/lsst/LSSWG/HumnaWindowFunctions

on NERSC. This makes the collaboration public. Humna, let me know if you object to this. 
But haven't looked at them yet carefully.

**Comment by slosar** [comment]
Renamed to HumnaDepthVariations due to complaint from Eric G.

**Comment by humnaawan** [comment]
Sorry for the late reply! @slosar I am okay with data being public. Let me know if anything else comes up.
