### ISSUE TITLE
Spectroscopy

### ISSUE THREAD

**Issue by dodelson** [DarkEnergyScienceCollaboration/2pt_validation#13]
@slosar We want to analyze the 3D distribution in addition to the 2D. Could you provide z_spec in the catalogs?

**Comment by slosar** [comment]
Sure, why do you need this for? The point of simple PZ was to make sure we don't overdo information (i.e. C(ell,z1,z2) have hard time competing with 3D P(k) in case of no errors). 
But if you want to focus on PZ effect alone (i.e. the project with smeared, etc), I can just give you the full 3D mocks (i.e. without any sky cuts, which makes Pk easier to computer + you get more SNR).

**Comment by dodelson** [comment]
I thought the SRM had implicit/explicit plans to do everything in 3D [or did that change?]. We'd like to compute the power spectrum/correlation function in 3D using spectroscopic redshifts and then photo-z to examine the degradation and consider optimal estimators for extracting it. We can also run on the 2D stuff alone as part of your current effort ["We" \equiv Nil Banik, student from Florida]

**Comment by slosar** [comment]
I though so as well, my first idea was to simply go to P(kperp,kpar,z), but this has downside of being model dependent and more importantly does not easily translate into cross-correlation business at least not the way we are used to think about it. I am pushing for something like C(ell,kpar,z) where kpar is Fourier koordinate of r=log(1+z) (so model independent in both directions), but there are also advantages to staying in C(ell,z1,z2). 
See also: 

https://confluence.slac.stanford.edu/display/LSSTDESC/LSS+1.1.2%3A+Data+Compression+Scheme

Anyway, you'll get something from me soon!

**Comment by slosar** [comment]
mkcat now has an option to also save true redhift, called --truez. It will just add the relevant column.
I need to regenerate those at nersc, but let's first create a few more options.
