### ISSUE TITLE
Inconsistent clustering between different mocks

### ISSUE THREAD

**Issue by damonge** [DarkEnergyScienceCollaboration/2pt_validation#22]
If I take the two mocks:

/project/projectdirs/lsst/LSSWG/LNMocks/160620+TrueZ+FullSky+realspace+subsamp_1000000/catalog6.h5

/project/projectdirs/lsst/LSSWG/LNMocks/160620+TrueZ+FullSky+realspace+subsamp_1000000/catalog10.h5

And compute the power spectrum for galaxies in the redshift bin 0.5<z<0.6 I get two completely inconsistent curves (see plot below). These are plain anafast power spectra, so nothing fancy.

I've inspected the 3D and 2D galaxy positions for these catalogs, but I couldn't see anything weird in them... It might be a good idea to check if this is reproduced by the original CoLoRe files, in order to isolate the bug.

![cls](https://cloud.githubusercontent.com/assets/8809493/16728666/afa6352c-475f-11e6-86a7-bac2739df8bb.png)

**Comment by damonge** [comment]
Ok, it seems to be there in CoLoRe, so that's where the bug is... I'll run a few tests to see what it's due to

**Comment by slosar** [comment]
It is also possible that there is a bug in running colore!!

Check out

./drive_CoLoRe/vc.py --help

## in 2pt_validation...

anže

**Comment by damonge** [comment]
Update: the problem seems to be in CoLoRe. I've been able to reproduce it using your param files. I think I've identified the source: high biases seem to make the lognormal transformation unstable (the problem goes away completely when I set the bias to 1).

I'm still a bit puzzled that this is such a big issue, so first I'm gonna try to figure out if this is purely numerical (and solvable) or whether this is really a fundamental limitation of the lognormal transformation. If the latter, the solution might be to smooth out the density field on a larger scale to avoid having high peaks.

**Comment by damonge** [comment]
Ok, I've confirmed this. I've run simulations with progressively larger smoothing scales, and the unstable behaviour of the lognormal disappears when you smooth with a kernel of ~5 Mpc/h.

There are probably other ways of fixing this (e.g. correcting the lognormal transformation for large values of delta_Gauss so it doesn't go crazy), but I think this is the most straightforward fix.

Thoughts?

**Comment by damonge** [comment]
Ok, the power spectrum in the new catalogs looks compatible now.
