### ISSUE TITLE
Create star contamination in fastcat/mkcat

### ISSUE THREAD

**Issue by slosar** [DarkEnergyScienceCollaboration/2pt_validation#5]
Stars are uniformly drawn from a healpix map of our galaxy + given some p(z), for the time being independent of angular position.

**Comment by fjaviersanchez** [comment]
Maybe we can use OpSim/CatSim. I have some code that reads the stars from CatSim:

```
import matplotlib.pyplot as plt
%matplotlib inline
import lsst.sims.maf.db as db
import lsst.sims.maf.metrics as metrics
import lsst.sims.maf.slicers as slicers
import lsst.sims.maf.metricBundles as metricBundles
import lsst.sims.maf.maps as maps
import numpy as np

opsdb = db.OpsimDatabase('minion_1016_sqlite.db') # LSST database required!
outDir = 'starMap_test'
resultsDb = db.ResultsDb(outDir=outDir)

bundleList = []
sql = 'night < %i' % (365.25*2.0)
slicer = slicers.HealpixSlicer(nside=64, useCache=False)
metric = metrics.StarDensityMetric(rmagLimit=27.5,metricName='rmag=28')
mafMap = maps.StellarDensityMap()
plotDict = {'colorMin':0.001, 'colorMax':.1, 'logScale':True}
bundle = metricBundles.MetricBundle(metric,slicer,sql, mapsList=[mafMap], plotDict=plotDict)
bundleList.append(bundle)
bundleDict = metricBundles.makeBundlesDictFromList(bundleList)

bgroup = metricBundles.MetricBundleGroup(bundleDict, opsdb, outDir=outDir, resultsDb=resultsDb)
bgroup.runAll()
bgroup.plotAll(closefigs=False)

masked_array = bundle.metricValues*3600
masked_array.mask = bundle.metricValues.mask
```

For the p(z) we can just go with a certain random distribution independent of the position.

**Comment by slosar** [comment]
Great!
How hard it is to install lsst python package?
Do we have it at NERSC? @richardxdubois : This is something where desc-wide installation at nersc would be most useful (i.e. if you could get the above code snippet running, we win :))
anze

**Comment by jchiang87** [comment]
@slosar: There is a shared Stack at NERSC recently installed via the lsst-sims conda distribution.  See https://github.com/DarkEnergyScienceCollaboration/Twinkles/issues/204#issuecomment-210599428

**Comment by fjaviersanchez** [comment]
The installation is pretty straightforward with anaconda and the instructions are really complete:

https://confluence.lsstcorp.org/display/SIM/Catalogs+and+MAF

**Comment by slosar** [comment]
Finally came around to have a look at this.
@jchiang87 : MAF installation at NERSC works great, thanks
@fjaviersanchez : Great, I managed to get it working. But where do I get the minion_1016_sqlite.db file? Also, since I wasn't able to run your snippet -- at some point we actually need ra-dec for those stars -- can we get them? I agree some gaussian PZ should be associated with them for a realistic contamination.

**Comment by fjaviersanchez** [comment]
The minion_1016_sqlite.db (or any other OpSim database) can be downloaded here:

http://lsst.org/scientists/simulations/opsim/opsim-v335-benchmark-surveys

I can upload to NERSC the actual stellar catalog (I don't know if the people from UW have it already there or they just have it in their server) or just the healpix maps with the stellar densities and use those maps to generate stars uniformly distributed within the pixel with certain gaussian PZ. Whatever works best.

**Comment by slosar** [comment]
@fjaviersanchez 
I'm super busy until next week, so why don't you put these files into NERSC project space (somewere /project/projectdirs/lsst/LSSWG/ if they are not already in that project space) and then extend fastcat_CoLore/mkcat.py to be able to add these stars -- just add rows with appropriate ra,dec and a redshift chosen from a wide gaussian 0.5+-0.1 or something and have some options for user to control what percentage of stars do you want to add?  You should have full commit rights.
Let me know if there are any issues or questions or if you refuse to do this? :)

**Comment by fjaviersanchez** [comment]
Ok! I will upload the stellar catalog to NERSC and modify mkcat :)

**Comment by fjaviersanchez** [comment]
I contacted Scott Daniel at UW and he made possible to access the CatSim database from Cori. I have tried to download the data several times from Cori but I had some trouble with the jobs (connection timeouts) so I am still trying to download everything. The code I am using to download it is this:

```
import numpy
from lsst.sims.catalogs.measures.instance import InstanceCatalog

class simpleStarCatalog(InstanceCatalog):
    column_outputs = ['raJ2000', 'decJ2000', 'simobjid','umag','gmag','rmag','imag','zmag','ymag']

    transformations = {'raJ2000':numpy.degrees, 'decJ2000':numpy.degrees}

from lsst.sims.utils import ObservationMetaData
from lsst.sims.catUtils.baseCatalogModels import StarObj
def query_patch(ra,dec,side,id):

    myObsMetadata = ObservationMetaData(pointingRA=ra, pointingDec=dec,
                                        boundType='circle', boundLength=side)

    starTableConnection = StarObj(host='fatboy.phys.washington.edu', port=1433)

    myCatalog = simpleStarCatalog(starTableConnection,
                                  obs_metadata = myObsMetadata)

    myCatalog.write_catalog('catsim_ra_dec_id_umag_gmag_rmag_imag_zmag_ymag_'+str(id)+'.dat')

x = numpy.linspace(2,358,90)
y = numpy.linspace(-178,178,90)
id=0
for ra in x:
    for dec in y:
        print ra, dec
        query_patch(ra,dec,2.0,id)
        id=id+1
        if(id%100==0):
            print id

```

In order to make it run in Cori you should add the following to your .bash_profile.ext

```
 if [ "$NERSC_HOST" == "cori" ]
 then
   source /project/projectdirs/lsst/lsstDM/Cori/11.0/loadLSST.bash
   source /project/projectdirs/lsst/lsstDM/Cori/setupfiles/setupWithLatestobs_lsstSim.sh
   setup lsst_sims
 fi
```

**Comment by jchiang87** [comment]
To workaround the connection issues, you can try enclosing the `simpleStarCatalog(...)` call in a loop, catching the `RuntimeError` until it succeeds, e.g.,

```
    while True:
        try:
            myCatalog = simpleStarCatalog(starTableConnection, obs_metadata=myObsMetadata)
            break
        except RuntimeError:
            continue
    myCatalog.write_catalog(...)
```

We had to do this for Twinkles, e.g., [here](https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/master/python/desc/twinkles/generatePhosimInput.py#L101).

**Comment by fjaviersanchez** [comment]
Thanks @jchiang87!

**Comment by slosar** [comment]
@jchiang87 : this clearly is a hack around something that probably has a better solution. :)
@fjaviersanchez : great to see movements, keep me posted with any progress or if things needs changing. We had long discussions with Johann, who had trouble decoding my intentions in the code, which is, admittedly, not as well documented as I would like it to be, so better ask if something is not clear...

**Comment by jchiang87** [comment]
@slosar I agree there should be a more elegant-looking solution, but to be honest, any client-side mitigation will look like this.  Dropped database connections, especially for remote resources, are going to happen, the question is where the code that deals with them lives.  I can certainly see something going into the `lsst.sims.catalogs` code to handle this. @danielsf  Any thoughts?

**Comment by danielsf** [comment]
One thought: `starTableConnection` is an instantiation of a class called `CatalogDBObject`, which both connects to the database and queries the table.  This means that every time `starTableConnection` is instantiated, you are opening a new connection to the database.  There is another class, `DBConnection` which is just a connection to the database.  You can pass these into `CatalogDBObject`s and thus reuse one connection for multiple catalog queries.  That way, once you open a connection, you shouldn't have to worry about subsequent connections timing out.  The code for that would look something like:

```
from lsst.sims.catalogs.generation.db import DBConnection

_db_connection = DBConnection(host='fatboy.phys.washington.edu', port=1433)

def query_patch(ra, dec, side, id):

    ...

    global _db_connection
    starTableConnection = StarObj(connection=_db_connection)

    ...
```

It doesn't actually deal with the problem of dropped connections, but it makes them less recurrent.

Do you have any of the error outputs from your dropped connections handy?  I would be interested to see them (email them to me at scottvalscott@gmail.com).  We had a lot of trouble with dropped connections about a year ago.  We thought that we had solved the problem.

**Comment by fjaviersanchez** [comment]
@danielsf The connection dropping happened to me when I was trying to make big queries (i.e. I was trying to download the whole catalog at once) and unfortunately I didn't keep the logs. To circumvent the problem I am trying with smaller queries (2 deg radius circles) and I didn't run into any other connection problem since then.

@slosar I will keep you posted. Right now I am still in the process of downloading the stellar catalog (and thus, not have to query everytime we run the code). Once I have it, I will try to modify mkcat.
