### ISSUE TITLE
Enable push access for the LSS working group Team

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/2pt_validation#9]
@tony-johnson I think @slosar would like the LSS working group to have push access to this repo. The LSS Team only has one member in it, though. Is it being auto-populated from people's DESC profiles? It would be great if you could activate that, if it isn't. Thanks! :-)

**Comment by tony-johnson** [comment]
The Large Scale Structure teams is now being synchronized to the DESC database, and contains 65 members. That team also now has read/write access to the 2pt_validation repository.

For reference the list of teams which is currently automatically synchronized is listed here:
https://confluence.slac.stanford.edu/x/YQTpCw

**Comment by drphilmarshall** [comment]
Great, thanks Tony! :-)
